#!/usr/bin/python3
# linuav is the new av upgrade to guardian.
import os
import stat
from banner import colors, banner
from hash_function import hashfun

def scan_directory_to_file(user_dir, output_file):
    '''This function is used to create the .txt files for storage and analysis. It filters out dynamically
    changing folders for linux. It also filters for non-executable modes on files and passes on
    only executable files.'''
    with open(output_file, 'w') as f:
        for dirpath, dirnames, filenames in os.walk(user_dir):
            for filename in filenames:
                path = os.path.join(dirpath, filename)
                if '/proc' in path or '/run' in path or '/tmp' in path:
                    continue
                else:
                    try:
                        stat_info = os.stat(path)
                        st_mode = stat_info.st_mode
                        permission_str = stat.filemode(st_mode)
                        if 'x' in permission_str:
                            f.write(path + '\n')
                    except:
                        pass
    
    print('\n',colors.BOLDYELLOW + 'Text file creation completed.. now what?' + colors.RESET,'\n')

    validate_input()

def find_new_x():
    '''This function takes the contents of .txt files and puts them in a list container.
    it then uses the list.remove() to remove all accounted for files from the second container
    leaving only the unknown files.'''
    while True:

        try:
            txt_file = input(colors.BOLDYELLOW + 'enter baseline file: ' + colors.RESET)
            print()
            file1 = open(txt_file)
            content = file1.read()
            break
    
        except:

            print(colors.BOLDRED + 'File not found! please try again.' + colors.RESET,'\n')

    content_list = content.split('\n')
    
    while True:

        try:

            txt_file2 = input(colors.BOLDYELLOW + 'enter scan file: ' + colors.RESET)
            print()
            file2 = open(txt_file2)
            content2 = file2.read()
            break

        except:

            print(colors.BOLDRED + 'File not found! please try again.' + colors.RESET,'\n')
    
    content_list2 = content2.split('\n')
    
    for file in content_list:
        try:
            
            content_list2.remove(file)
        except:
            pass 
    
    print(colors.BOLDBLACK + '==Potential======Malwares======Listed========Below============' + colors.RESET,'\n')
    
    count = 0
    for execs in content_list2:
        print(colors.BOLDRED + 'potential malware found:',execs + colors.RESET)
        count += 1

    print()

    print(colors.BOLDBLACK + '==============================================================' + colors.RESET)

    if count == 0:
    
        print('\n','There are:',colors.BOLDGREEN ,count, colors.RESET,' Potential Malwares detected, listed above.','\n')

    else:

        print('\n','There are:',colors.BOLDRED  ,count, colors.RESET,' Potential Malwares detected, listed above.','\n')


    print(colors.BOLDYELLOW + 'Reminder!: not all found files are malware.','\n'
          ' You may have downloaded an app and forgot to update your baseline.txt file.','\n'
          ' or if you run sudo apt update and forget to update your baseline.txt all those files','\n'
          ' will show up in the next scan.'+ colors.RESET,'\n')

    print('\n',colors.BOLDGREEN + 'Scan completed.. now what?' + colors.RESET,'\n')

    validate_input()


def help_menu():
    '''This functions as a description and instructions'''
    print('linuAV helps strengthin your security posture.','\n'
          'while tools like "ClamAV" and "chkrootkit" check for KNOWN signatures','\n'
          'linuAV will check for ALL NEW malwares not yet defined by other AV\'s','\n'
          'When used together in unison any linux will be more protected than ever.','\n','\n' 
          'How you ask? This tool creates a baseline file of your','\n'
          'system "ideally disease free".','\n','\n'
          'You will want to create your baseline file before you visit a','\n'
          'random/sketchy site or download something from the internet;','\n'
          'linuAV will show you all NEW files added to your OS using linuAV\'s','\n'
          'scanfile option, this will let you view the file path of the new','\n'
          'potential malware.','\n','\n'
          '*It is up to you on how you use the information presented to you*','\n','\n'
          'This program was created on a kali linux for all linux users.','\n','\n'
          'LET\'S GO STEP BY STEP:','\n','\n'
          'Step one: Creating your baseline file','\n','\n'
          '     Press 1, enter root dir "/", name file [baseline.txt]','\n'
          'hit enter and wait for return of options menu. The file will be','\n'
          'stored in the same directory as linuAV.','\n','\n'
          '     ****"If its your first time using, after your text file is','\n'
          'created exit "q" program".*****','\n','\n'
          '     -If returning start at step two-','\n','\n'
          '     *Only after* you roam the internet and want to check for any','\n'
          'drive-by malwares or to just view where a new file has been downloaded','\n'
          'you will continue on to making your scan file.','\n','\n'
          'Step two: Now create your scan file','\n','\n'
          'Repeat process','\n'
          '     Press 1, enter root dir "/", now name scan file [scanfile.txt]','\n','\n'
          'Step three: Next we compare your baseline file to your scan file','\n','\n'
          '     Press 2, type baseline.txt, hit enter, type scanfile.txt, hit enter,','\n','\n'
          'wait for results.','\n','\n'
          'Note: If you download a new program, that you believe is trust worthy,','\n'
          'you will have to update your baseline file "baseline.txt" or it will','\n'
          'show up as possible malware in the next scan.')
    
    print(colors.BOLDGREEN + 'Help completed.. now what?' + colors.RESET,'\n')

    validate_input()


def validate_input():
    '''This function acts as the main menu of the program and input validator.'''
    print(colors.BOLDGREEN + '#########################' + colors.RESET)
    print(colors.BOLDGREEN + '                        #' + colors.RESET)
    print(colors.BOLDGREEN + 'press 1 to make a file. #################' + colors.RESET)
    print(colors.BOLDGREEN + '                                        #' + colors.RESET)
    print(colors.BOLDGREEN + 'press 2 to scan files.                  #' + colors.RESET)
    print(colors.BOLDGREEN + '                                        #' + colors.RESET)
    print(colors.BOLDGREEN + 'press 3 to hash a file.                 #' + colors.RESET)
    print(colors.BOLDGREEN + '                                        #' + colors.RESET)
    print(colors.BOLDGREEN + 'press \'h\' for help and welcome message. #       l i n u A V     V.1.0.1' + colors.RESET)
    print(colors.BOLDGREEN + '                                        #' + colors.RESET) 
    print(colors.BOLDGREEN + 'press \'q\' to quit.                      #' + colors.RESET)
    print(colors.BOLDGREEN + '                     ####################' + colors.RESET)
    print(colors.BOLDGREEN + '######################' + colors.RESET,'\n')

    while True:

        sel = input(colors.BOLDYELLOW + '> ' + colors.RESET)

        if sel == '1':

            print(colors.BOLDBLUE + 'Helpful tip: the dir prompt will not check for misspelled directories,','\n'
            'so if you are selecting a directory other than root "/", make sure it is','\n'
            'properly spelled and use a full path if folder is not in same dir as linuAV.' + colors.RESET,'\n')

            root_dir = input(colors.BOLDYELLOW + 'dir: ' + colors.RESET)
            out_file = input(colors.BOLDYELLOW + 'name your file: ' + colors.RESET)
            scan_directory_to_file(root_dir, out_file)

        elif sel == '2':
            find_new_x()

        elif sel == '3':
            hashfun()
            continue

        elif sel == 'h':
            help_menu()

        elif sel == 'q':
            print(colors.BOLDGREEN + 'Thank you for using linuAV!' + colors.RESET)
            exit()

        print(colors.BOLDRED + 'Invalid Selection: 1, 2, h or q please' + colors.RESET)

def main():
    '''this is the linuAV program'''

    banner()

    validate_input()

if __name__ == "__main__":
    main()
